### ISSUE TITLE
Estimated date for code release?

### ISSUE THREAD

**Issue by emilyeros** [VIDA-NYU/tile2net#1]
Do you have an expected date to release this code?

I've been eagerly awaiting the code release so I can try this out and test performance on a couple of additional cities that the tool wasn't trained on. I noticed that the code wasn't released on Friday, and the readme no longer has an expected date. Any news?

Thanks!

**Comment by Knollentuin** [comment]
Same here, really would like to try the model on different data.

**Comment by Mary-h86** [comment]
Thank you both for your interest! 
We are updating the codes and documentation to work with the new PyTorch stable version (2.0.0) and Shapely 2! It is difficult to give an exact date, but we are doing our best to release the code as soon as possible (hopefully by the end of March).

Please note that the model may need additional training if the urban fabric/built environment of the region you want to try it on is very different from the US context. However, the required training set will be significantly smaller than what would otherwise be needed.

**Comment by Mary-h86** [comment]
Thank you!

**Comment by Knollentuin** [comment]
Thanks for the update. Useful improvements indeed!
