### ISSUE TITLE
No segmentation output

### ISSUE THREAD

**Issue by DanielRose2310** [VIDA-NYU/tile2net#43]
I've ran the example and using custom data from the command line. The tiles and network are generated correctly but no segmentation result. \seg_results\ is empty in all cases. No errors or warnings.

**Comment by dhodcz2** [comment]
Could you please include the command that you ran, and a sample image with its file path?

**Comment by Mary-h86** [comment]
@DanielRose2310 

That’s the expected behavior now. The segmentation results are only for quality control since they are not our main outputs, and having thousands of image+labels being saved on your drive is not in most cases desirable! In our recent updates, we decided not to make saving side by side image+labels the default behavior. However, we will add a command-line switch to turn this on or off as needed and will make sure that the extra folder doesn't get created if you're not using the feature in the next update. Keep an eye out for it!

**Comment by DanielRose2310** [comment]
> @DanielRose2310
> 
> That’s the expected behavior now. The segmentation results are only for quality control since they are not our main outputs, and having thousands of image+labels being saved on your drive is not in most cases desirable! In our recent updates, we decided not to make saving side by side image+labels the default behavior. However, we will add a command-line switch to turn this on or off as needed and will make sure that the extra folder doesn't get created if you're not using the feature in the next update. Keep an eye out for it!

Thanks for your response. I think having it as a feature would be valuable.
